-- A tiered view has no INSTEAD OF INSERT trigger. The post_parse_analyze hook
-- is the one write path: it rewrites a top-level INSERT off the view before the
-- rewriter runs, and a write that reaches the view any other way (a COPY, an
-- INSERT nested in WITH) fails in PostgreSQL instead of landing rows that
-- skipped the hook.
-- Suppress the run-order-dependent "already exists" NOTICE: in the shared
-- regress db an earlier test may have created the extensions, standalone not.
SET client_min_messages = warning;
CREATE EXTENSION IF NOT EXISTS pg_duckdb;
CREATE EXTENSION IF NOT EXISTS coldfront;
RESET client_min_messages;

SET TIME ZONE 'UTC';
-- White-box: checks the hooks' SQL/DDL, not Iceberg I/O. Real cold I/O is ci/journey.sh; see README.md.
SET coldfront.warehouse = '';
SET coldfront.lakekeeper_endpoint = '';
SET coldfront.dblink_self = '';

CREATE TABLE public._events (
    id     bigint GENERATED BY DEFAULT AS IDENTITY,
    ts     timestamptz NOT NULL,
    status text NOT NULL DEFAULT 'new'
);
CREATE VIEW public.events AS SELECT id, ts, status FROM public._events;
INSERT INTO coldfront.tiered_views(schema_name, relname, hot_table, iceberg_table, partition_col)
VALUES ('public', 'events', 'public._events', 'ice.default.events', 'ts');
INSERT INTO coldfront.archive_watermark(schema_name, table_name, cutoff_time)
VALUES ('public', 'events', '2026-03-01'::timestamptz);

-- The view a DDL rebuild leaves behind (here after a rename, which the hook
-- follows with a rebuild) has its cold branch and no trigger, and the extension
-- has no builder for one.
ALTER VIEW public.events RENAME TO events_v2;
SELECT pg_get_viewdef('public.events_v2'::regclass) LIKE '%iceberg_scan%' AS has_cold_branch;
SELECT count(*) AS triggers FROM pg_trigger
 WHERE tgrelid = 'public.events_v2'::regclass AND NOT tgisinternal;
SELECT to_regproc('coldfront._rebuild_write_trigger') IS NULL              AS no_builder,
       to_regprocedure('coldfront._cold_placeholder(text)') IS NULL        AS no_placeholder_helper,
       to_regprocedure('coldfront._cold_value(text, text)') IS NULL        AS no_value_helper;

-- A hot INSERT through the hook lands with the heap's identity and default values.
INSERT INTO public.events_v2 (ts) VALUES ('2026-04-01');
SELECT id, status FROM public._events;

-- Writes the hook does not rewrite fail in PostgreSQL, and nothing lands.
COPY public.events_v2 (ts, status) FROM stdin;
2026-01-01 00:00:00+00	copied
\.
WITH i AS (INSERT INTO public.events_v2 (ts, status) VALUES ('2026-01-01', 'nested') RETURNING id)
SELECT count(*) FROM i;
SELECT count(*) AS rows_after FROM public._events;

-- Cleanup.
DELETE FROM coldfront.tiered_views;
DELETE FROM coldfront.archive_watermark;
DROP VIEW public.events_v2;
DROP TABLE public._events;
